-- Main grants table
CREATE TABLE grants (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  source TEXT NOT NULL,                 -- 'EU Portal', 'Balcão Fundos', 'FCT', 'EUFunding'
  source_url TEXT NOT NULL,
  amount TEXT,
  deadline DATE,
  relevance INTEGER DEFAULT 0,          -- 0-100 AI match score
  status TEXT DEFAULT 'active',         -- 'active', 'closing_soon', 'closed'
  region TEXT,                          -- 'EU', 'Portugal', 'Other'
  country TEXT,
  eligibility TEXT,
  contact TEXT,
  category TEXT,                        -- 'AI', 'Web3', 'OEPUGenAI'
  raw_data JSONB,
  days_left INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Deep research data (Gemini 2.5 Pro + AI-Researcher)
CREATE TABLE research_data (
  id SERIAL PRIMARY KEY,
  grant_id INTEGER REFERENCES grants(id) ON DELETE CASCADE,
  business_model TEXT,                  -- Generated by Gemini
  business_canvas_url TEXT,             -- Generated canvas image
  success_factors JSONB,                -- Critical success factors
  evaluation_criteria JSONB,            -- How grant is evaluated
  past_winners JSONB,                   -- Analysis of past winners
  deep_research JSONB,                  -- Full Gemini deep research output
  created_at TIMESTAMP DEFAULT NOW()
);

-- Generated proposals (DUAL MODE)
CREATE TABLE proposals (
  id SERIAL PRIMARY KEY,
  grant_id INTEGER REFERENCES grants(id) ON DELETE CASCADE,
  mode TEXT NOT NULL,                   -- 'fast' or 'research' (CRITICAL!)
  executive_summary TEXT,
  full_proposal TEXT,                   -- Markdown format
  budget JSONB,
  timeline JSONB,
  status TEXT DEFAULT 'draft',
  gemini_model TEXT DEFAULT 'gemini-2.0-flash-exp',
  generation_time INTEGER,              -- seconds
  enhanced_features JSONB,              -- Which of 43 features applied
  created_at TIMESTAMP DEFAULT NOW()
);

-- Multi-agent thinktank sessions
CREATE TABLE thinktank_sessions (
  id SERIAL PRIMARY KEY,
  grant_id INTEGER REFERENCES grants(id) ON DELETE CASCADE,
  researchers JSONB,                    -- 5 AI agents
  messages JSONB,                       -- Full conversation
  status TEXT DEFAULT 'active',
  final_output TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

-- Indexes
CREATE INDEX idx_grants_status ON grants(status);
CREATE INDEX idx_grants_deadline ON grants(deadline);
CREATE INDEX idx_grants_category ON grants(category);
CREATE INDEX idx_research_grant_id ON research_data(grant_id);
CREATE INDEX idx_proposals_grant_id ON proposals(grant_id);

-- Auto-update trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_grants_updated_at BEFORE UPDATE
ON grants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
