-- Main grants table
CREATE TABLE IF NOT EXISTS grants (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  source TEXT NOT NULL,                 -- 'EU Portal', 'Balcão Fundos', 'FCT', 'EUFunding'
  source_url TEXT NOT NULL,
  amount TEXT,
  deadline DATE,
  relevance INTEGER DEFAULT 0,          -- 0-100 AI match score
  status TEXT DEFAULT 'active',         -- 'active', 'closing_soon', 'closed'
  region TEXT,                          -- 'EU', 'Portugal', 'Other'
  country TEXT,
  eligibility TEXT,
  contact TEXT,
  category TEXT,                        -- 'AI', 'Web3', 'OEPUGenAI'
  raw_data JSONB,
  days_left INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Deep research data (Gemini 2.5 Pro + AI-Researcher)
CREATE TABLE IF NOT EXISTS research_data (
  id SERIAL PRIMARY KEY,
  grant_id INTEGER REFERENCES grants(id) ON DELETE CASCADE,
  business_model TEXT,                  -- Generated by Gemini
  business_canvas_url TEXT,             -- Generated canvas image
  success_factors JSONB,                -- Critical success factors
  evaluation_criteria JSONB,            -- How grant is evaluated
  past_winners JSONB,                   -- Analysis of past winners
  deep_research JSONB,                  -- Full Gemini deep research output
  created_at TIMESTAMP DEFAULT NOW()
);

-- Generated proposals (DUAL MODE)
CREATE TABLE IF NOT EXISTS proposals (
  id SERIAL PRIMARY KEY,
  grant_id INTEGER REFERENCES grants(id) ON DELETE CASCADE,
  mode TEXT NOT NULL,                   -- 'fast' or 'research' (CRITICAL!)
  executive_summary TEXT,
  full_proposal TEXT,                   -- Markdown format
  budget JSONB,
  timeline JSONB,
  status TEXT DEFAULT 'draft',
  gemini_model TEXT DEFAULT 'gemini-2.0-flash-exp',
  generation_time INTEGER,              -- seconds
  enhanced_features JSONB,              -- Which of 43 features applied
  created_at TIMESTAMP DEFAULT NOW()
);

-- Multi-agent thinktank sessions
CREATE TABLE IF NOT EXISTS thinktank_sessions (
  id SERIAL PRIMARY KEY,
  grant_id INTEGER REFERENCES grants(id) ON DELETE CASCADE,
  researchers JSONB,                    -- 5 AI agents
  messages JSONB,                       -- Full conversation
  status TEXT DEFAULT 'active',
  final_output TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP
);

-- Stripe Customers (Standard Supabase SaaS Schema)
CREATE TABLE IF NOT EXISTS customers (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  stripe_customer_id TEXT
);

-- Stripe Subscriptions (Standard Supabase SaaS Schema)
CREATE TABLE IF NOT EXISTS subscriptions (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  status TEXT,
  metadata JSONB,
  price_id TEXT,
  quantity INTEGER,
  cancel_at_period_end BOOLEAN,
  created TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  current_period_start TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  current_period_end TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  cancel_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  canceled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  trial_start TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  trial_end TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_grants_status ON grants(status);
CREATE INDEX IF NOT EXISTS idx_grants_deadline ON grants(deadline);
CREATE INDEX IF NOT EXISTS idx_grants_category ON grants(category);
CREATE INDEX IF NOT EXISTS idx_research_grant_id ON research_data(grant_id);
CREATE INDEX IF NOT EXISTS idx_proposals_grant_id ON proposals(grant_id);

-- Auto-update trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_grants_updated_at ON grants;
CREATE TRIGGER update_grants_updated_at BEFORE UPDATE
ON grants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Phase 1: Grant Discovery System
CREATE TABLE IF NOT EXISTS grant_sources (
    id SERIAL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    name TEXT,
    type TEXT, -- 'portal', 'aggregator', 'direct'
    last_crawled_at TIMESTAMP,
    status TEXT DEFAULT 'active'
);

-- Grant Discovery columns
ALTER TABLE grants ADD COLUMN IF NOT EXISTS relevance_score INTEGER DEFAULT 0;
ALTER TABLE grants ADD COLUMN IF NOT EXISTS keywords TEXT[];
ALTER TABLE grants ADD COLUMN IF NOT EXISTS discovered_at TIMESTAMP DEFAULT NOW();
ALTER TABLE grants ADD COLUMN IF NOT EXISTS source_id INTEGER REFERENCES grant_sources(id);

-- Ensure uniqueness for automated discovery
ALTER TABLE grants DROP CONSTRAINT IF EXISTS unique_source_url;
ALTER TABLE grants ADD CONSTRAINT unique_source_url UNIQUE (source_url);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE thinktank_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Using DO blocks to check existence before creating

-- Grants
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'grants' AND policyname = 'Public grants are viewable by everyone'
    ) THEN
        CREATE POLICY "Public grants are viewable by everyone" ON grants
        FOR SELECT USING (true);
    END IF;

    -- Allow writes for authenticated users (or service role which bypasses RLS)
    -- For now, we allow public insert/update to ensure backend works if using anon key
    -- In production, this should be restricted to service role or admin users
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'grants' AND policyname = 'Enable insert for everyone'
    ) THEN
        CREATE POLICY "Enable insert for everyone" ON grants FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'grants' AND policyname = 'Enable update for everyone'
    ) THEN
        CREATE POLICY "Enable update for everyone" ON grants FOR UPDATE USING (true);
    END IF;
END
$$;

-- Research Data
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'research_data' AND policyname = 'Research data is viewable by everyone'
    ) THEN
        CREATE POLICY "Research data is viewable by everyone" ON research_data
        FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'research_data' AND policyname = 'Enable insert for everyone'
    ) THEN
        CREATE POLICY "Enable insert for everyone" ON research_data FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'research_data' AND policyname = 'Enable update for everyone'
    ) THEN
        CREATE POLICY "Enable update for everyone" ON research_data FOR UPDATE USING (true);
    END IF;
END
$$;

-- Proposals
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'proposals' AND policyname = 'Proposals are viewable by everyone'
    ) THEN
        CREATE POLICY "Proposals are viewable by everyone" ON proposals
        FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'proposals' AND policyname = 'Enable insert for everyone'
    ) THEN
        CREATE POLICY "Enable insert for everyone" ON proposals FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'proposals' AND policyname = 'Enable update for everyone'
    ) THEN
        CREATE POLICY "Enable update for everyone" ON proposals FOR UPDATE USING (true);
    END IF;
END
$$;

-- Thinktank Sessions
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'thinktank_sessions' AND policyname = 'Thinktank sessions are viewable by everyone'
    ) THEN
        CREATE POLICY "Thinktank sessions are viewable by everyone" ON thinktank_sessions
        FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'thinktank_sessions' AND policyname = 'Enable insert for everyone'
    ) THEN
        CREATE POLICY "Enable insert for everyone" ON thinktank_sessions FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'thinktank_sessions' AND policyname = 'Enable update for everyone'
    ) THEN
        CREATE POLICY "Enable update for everyone" ON thinktank_sessions FOR UPDATE USING (true);
    END IF;
END
$$;

-- Customers
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'customers' AND policyname = 'Can view own customer data'
    ) THEN
        CREATE POLICY "Can view own customer data" ON customers
        FOR SELECT USING (auth.uid() = id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'customers' AND policyname = 'Can insert own customer data'
    ) THEN
        CREATE POLICY "Can insert own customer data" ON customers FOR INSERT WITH CHECK (auth.uid() = id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'customers' AND policyname = 'Can update own customer data'
    ) THEN
        CREATE POLICY "Can update own customer data" ON customers FOR UPDATE USING (auth.uid() = id);
    END IF;
END
$$;

-- Subscriptions
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'subscriptions' AND policyname = 'Can view own subscription data'
    ) THEN
        CREATE POLICY "Can view own subscription data" ON subscriptions
        FOR SELECT USING (auth.uid() = user_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'subscriptions' AND policyname = 'Can insert own subscription data'
    ) THEN
        CREATE POLICY "Can insert own subscription data" ON subscriptions FOR INSERT WITH CHECK (auth.uid() = user_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'subscriptions' AND policyname = 'Can update own subscription data'
    ) THEN
        CREATE POLICY "Can update own subscription data" ON subscriptions FOR UPDATE USING (auth.uid() = user_id);
    END IF;
END
$$;
